#!/bin/bash

APP_NAME="Sleep Timer"
BUNDLE_ID="com.sleeptimer.app"
BUILD_DIR=".build/release"
APP_DIR="$APP_NAME.app"

# Determine version
if [ -n "$GITHUB_ACTIONS" ] || [ -n "$CI" ]; then
    # In CI (GitHub Actions): use git tag
    VERSION=$(git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//')
    if [ -z "$VERSION" ]; then
        echo "⚠️  No git tag found in CI, using default version 1.0.0"
        VERSION="1.0.0"
    else
        echo "📦 Building version: $VERSION (from git tag)"
    fi
else
    # Local build: use fixed development version
    VERSION="dev"
    echo "🔨 Building local development version: $VERSION"
fi

# Generate assets (Assets.car and AppIcon.icns)
if [ -f "./generate-assets.sh" ]; then
    echo "Generating compiled assets..."
    chmod +x ./generate-assets.sh
    ./generate-assets.sh
fi

echo "Building Sleep Timer for release..."
swift build -c release

if [ $? -ne 0 ]; then
    echo "Build failed!"
    exit 1
fi

echo "Creating app bundle..."

# Remove old app if exists
rm -rf "$APP_DIR"

# Create app bundle structure
mkdir -p "$APP_DIR/Contents/MacOS"
mkdir -p "$APP_DIR/Contents/Resources"

# Copy binary
cp "$BUILD_DIR/SleepTimer" "$APP_DIR/Contents/MacOS/SleepTimer"

# Copy compiled assets
if [ -f "Resources/Assets.car" ]; then
    cp "Resources/Assets.car" "$APP_DIR/Contents/Resources/Assets.car"
fi

# Copy icon (generated by actool)
if [ -f "Resources/AppIcon.icns" ]; then
    cp "Resources/AppIcon.icns" "$APP_DIR/Contents/Resources/AppIcon.icns"
fi

# Generate Info.plist with version from git tag
cat > "$APP_DIR/Contents/Info.plist" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleExecutable</key>
	<string>SleepTimer</string>
	<key>CFBundleIconFile</key>
	<string>AppIcon</string>
	<key>CFBundleIdentifier</key>
	<string>$BUNDLE_ID</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$APP_NAME</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$VERSION</string>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>LSMinimumSystemVersion</key>
	<string>13.0</string>
	<key>LSUIElement</key>
	<true/>
	<key>NSCameraUsageDescription</key>
	<string>Sleep Timer uses your camera to detect when you fall asleep by tracking your eye closure.</string>
	<key>NSPrincipalClass</key>
	<string>NSApplication</string>
</dict>
</plist>
EOF

echo "✅ App bundle created successfully: $APP_DIR"

# Ad-hoc re-sign the assembled bundle. swift build signs only the executable;
# adding Info.plist and Resources afterwards invalidates that signature, so the
# bundle needs a fresh signature with matching CodeResources for Gatekeeper/Finder.
echo "🔏 Ad-hoc signing the bundle..."
codesign --force --deep --sign - "$APP_DIR"

# Remove quarantine attribute if running locally (not in CI)
if [ -z "$CI" ]; then
    echo "🔓 Removing quarantine attribute..."
    xattr -cr "$APP_DIR" 2>/dev/null || true
fi

echo "✅ App is ready to use"

echo ""
echo "To install, drag '$APP_DIR' to your Applications folder or run:"
echo "  mv '$APP_DIR' /Applications/"
echo ""
echo "To run now:"
echo "  open '$APP_DIR'"
