#!/bin/bash

APP_NAME="Watch Me While I Fall Asleep"
BUNDLE_ID="com.wiltodelta.watchmesleep"
BUILD_DIR=".build/release"
APP_DIR="$APP_NAME.app"

# Determine version
if [ -n "$GITHUB_ACTIONS" ] || [ -n "$CI" ]; then
    # In CI (GitHub Actions): use git tag
    VERSION=$(git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//')
    if [ -z "$VERSION" ]; then
        echo "⚠️  No git tag found in CI, using default version 1.0.0"
        VERSION="1.0.0"
    else
        echo "📦 Building version: $VERSION (from git tag)"
    fi
else
    # Local build: use fixed development version
    VERSION="dev"
    echo "🔨 Building local development version: $VERSION"
fi

# Generate assets (Assets.car and AppIcon.icns)
if [ -f "./generate-assets.sh" ]; then
    echo "Generating compiled assets..."
    chmod +x ./generate-assets.sh
    ./generate-assets.sh
fi

echo "Building Watch Me While I Fall Asleep for release..."
# Apple silicon only: no x86_64 slice is built. The SDK version stamp lives in
# Package.swift, so every build path gets it.
MACOS_MIN=$(sed -n 's/^let deploymentTarget = "\(.*\)"$/\1/p' Package.swift)
swift build -c release --arch arm64

if [ $? -ne 0 ]; then
    echo "Build failed!"
    exit 1
fi

echo "Creating app bundle..."

# Remove old app if exists
rm -rf "$APP_DIR"

# Create app bundle structure
mkdir -p "$APP_DIR/Contents/MacOS"
mkdir -p "$APP_DIR/Contents/Resources"

# Copy binary
cp "$BUILD_DIR/WatchMeSleep" "$APP_DIR/Contents/MacOS/WatchMeSleep"

# Copy compiled assets
if [ -f "Resources/Assets.car" ]; then
    cp "Resources/Assets.car" "$APP_DIR/Contents/Resources/Assets.car"
fi

# Copy icon (generated by actool)
if [ -f "Resources/AppIcon.icns" ]; then
    cp "Resources/AppIcon.icns" "$APP_DIR/Contents/Resources/AppIcon.icns"
fi

# Generate Info.plist with version from git tag
cat > "$APP_DIR/Contents/Info.plist" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleExecutable</key>
	<string>WatchMeSleep</string>
	<key>CFBundleIconFile</key>
	<string>AppIcon</string>
	<key>CFBundleIdentifier</key>
	<string>$BUNDLE_ID</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$APP_NAME</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$VERSION</string>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>LSMinimumSystemVersion</key>
	<string>$MACOS_MIN</string>
	<key>LSUIElement</key>
	<true/>
	<key>NSCameraUsageDescription</key>
	<string>Watch Me While I Fall Asleep uses your camera to detect when you fall asleep by tracking your eye closure.</string>
	<key>NSPrincipalClass</key>
	<string>NSApplication</string>
</dict>
</plist>
EOF

echo "✅ App bundle created successfully: $APP_DIR"

# Re-sign the assembled bundle. swift build signs only the executable; adding
# Info.plist and Resources afterwards invalidates that signature, so the bundle
# needs a fresh signature with matching CodeResources for Gatekeeper/Finder.
#
# Sign with the team's Developer ID Application identity when the keychain has it:
# its stable designated requirement keeps the Camera (TCC) grant across rebuilds
# and releases, and with the hardened runtime, the camera entitlement and
# (RELEASE=1) a secure timestamp it is what notarization requires (notarize.sh).
# The timestamp needs Apple's server, so everyday builds skip it and still work
# offline. Without the identity (contributors, CI branch builds) the bundle is
# signed ad hoc, which runs but re-prompts for camera access after every rebuild.
TEAM_ID="K2GT9Q4S6U"
ENTITLEMENTS="Resources/WatchMeSleep.entitlements"
SIGN_IDENTITY="$(security find-identity -v -p codesigning 2>/dev/null \
    | awk -F'"' -v team="($TEAM_ID)" '/Developer ID Application:/ && index($2, team) {print $2; exit}')"
if [ -n "$SIGN_IDENTITY" ]; then
    TIMESTAMP="--timestamp=none"
    [ "${RELEASE:-}" = 1 ] && TIMESTAMP="--timestamp"
    codesign --force --options runtime --entitlements "$ENTITLEMENTS" "$TIMESTAMP" \
        --sign "$SIGN_IDENTITY" "$APP_DIR" || exit 1
    echo "🔏 Signed the bundle with '$SIGN_IDENTITY'."
elif [ "${RELEASE:-}" = 1 ]; then
    echo "error: RELEASE=1 but no Developer ID Application identity for team $TEAM_ID" >&2
    exit 1
else
    echo "🔏 Ad-hoc signing the bundle (Camera access will re-prompt on relaunch)..."
    codesign --force --entitlements "$ENTITLEMENTS" --sign - "$APP_DIR" || exit 1
fi

# Remove quarantine attribute if running locally (not in CI)
if [ -z "$CI" ]; then
    echo "🔓 Removing quarantine attribute..."
    xattr -cr "$APP_DIR" 2>/dev/null || true
fi

echo "✅ App is ready to use"

echo ""
echo "To install, drag '$APP_DIR' to your Applications folder or run:"
echo "  mv '$APP_DIR' /Applications/"
echo ""
echo "To run now:"
echo "  open '$APP_DIR'"
