#!/bin/bash

APP_NAME="Watch Me While I Fall Asleep"
BUNDLE_ID="com.wiltodelta.watchmesleep"
BUILD_DIR=".build/release"
APP_DIR="$APP_NAME.app"

# Determine version
if [ -n "$GITHUB_ACTIONS" ] || [ -n "$CI" ]; then
    # In CI (GitHub Actions): use git tag
    VERSION=$(git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//')
    if [ -z "$VERSION" ]; then
        echo "⚠️  No git tag found in CI, using default version 1.0.0"
        VERSION="1.0.0"
    else
        echo "📦 Building version: $VERSION (from git tag)"
    fi
else
    # Local build: use fixed development version
    VERSION="dev"
    echo "🔨 Building local development version: $VERSION"
fi

# Generate assets (Assets.car and AppIcon.icns)
if [ -f "./generate-assets.sh" ]; then
    echo "Generating compiled assets..."
    chmod +x ./generate-assets.sh
    ./generate-assets.sh
fi

echo "Building Watch Me While I Fall Asleep for release..."
swift build -c release

if [ $? -ne 0 ]; then
    echo "Build failed!"
    exit 1
fi

echo "Creating app bundle..."

# Remove old app if exists
rm -rf "$APP_DIR"

# Create app bundle structure
mkdir -p "$APP_DIR/Contents/MacOS"
mkdir -p "$APP_DIR/Contents/Resources"

# Copy binary
cp "$BUILD_DIR/WatchMeSleep" "$APP_DIR/Contents/MacOS/WatchMeSleep"

# Copy compiled assets
if [ -f "Resources/Assets.car" ]; then
    cp "Resources/Assets.car" "$APP_DIR/Contents/Resources/Assets.car"
fi

# Copy icon (generated by actool)
if [ -f "Resources/AppIcon.icns" ]; then
    cp "Resources/AppIcon.icns" "$APP_DIR/Contents/Resources/AppIcon.icns"
fi

# Generate Info.plist with version from git tag
cat > "$APP_DIR/Contents/Info.plist" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleExecutable</key>
	<string>WatchMeSleep</string>
	<key>CFBundleIconFile</key>
	<string>AppIcon</string>
	<key>CFBundleIdentifier</key>
	<string>$BUNDLE_ID</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$APP_NAME</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$VERSION</string>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>LSMinimumSystemVersion</key>
	<string>13.0</string>
	<key>LSUIElement</key>
	<true/>
	<key>NSCameraUsageDescription</key>
	<string>Watch Me While I Fall Asleep uses your camera to detect when you fall asleep by tracking your eye closure.</string>
	<key>NSPrincipalClass</key>
	<string>NSApplication</string>
</dict>
</plist>
EOF

echo "✅ App bundle created successfully: $APP_DIR"

# Re-sign the assembled bundle. swift build signs only the executable; adding
# Info.plist and Resources afterwards invalidates that signature, so the bundle
# needs a fresh signature with matching CodeResources for Gatekeeper/Finder.
#
# Prefer a stable self-signed identity so the Camera (TCC) grant persists across
# rebuilds; fall back to ad-hoc when it is missing (e.g. in CI), which makes
# macOS re-prompt for camera access. Recreate the identity once with:
#   openssl req -x509 -newkey rsa:2048 -keyout k.key -out c.crt -days 3650 -nodes \
#     -subj "/CN=$SIGN_IDENTITY" -addext "extendedKeyUsage=critical,codeSigning"
#   openssl pkcs12 -export -out c.p12 -inkey k.key -in c.crt -passout pass:wms \
#     -name "$SIGN_IDENTITY" -macalg sha1 -keypbe PBE-SHA1-3DES -certpbe PBE-SHA1-3DES
#   security import c.p12 -k ~/Library/Keychains/login.keychain-db -P wms -A
SIGN_IDENTITY="Watch Me While I Fall Asleep Dev"
if security find-identity -p codesigning 2>/dev/null | grep -q "$SIGN_IDENTITY" \
    && codesign --force --deep --sign "$SIGN_IDENTITY" "$APP_DIR" 2>/dev/null; then
    echo "🔏 Signed the bundle with '$SIGN_IDENTITY'."
else
    echo "🔏 Ad-hoc signing the bundle (Camera access will re-prompt on relaunch)..."
    codesign --force --deep --sign - "$APP_DIR"
fi

# Remove quarantine attribute if running locally (not in CI)
if [ -z "$CI" ]; then
    echo "🔓 Removing quarantine attribute..."
    xattr -cr "$APP_DIR" 2>/dev/null || true
fi

echo "✅ App is ready to use"

echo ""
echo "To install, drag '$APP_DIR' to your Applications folder or run:"
echo "  mv '$APP_DIR' /Applications/"
echo ""
echo "To run now:"
echo "  open '$APP_DIR'"
